Exit code: 0
Wall time: 0.5 seconds
Output:
const P={基本:['プレー時間（分）','試合数'],攻撃:['トライ','得点','ボールキャリー','ゲインメーター','ラインブレイク','ディフェンス突破','オフロードパス','トライアシスト','パス'],'守備&ディシプリン':['タックル','タックルミス','タックル成功','被ターンオーバー','シンビン','レッドカード'],キック:['インプレーキック','ペナルティゴール','PKミス','ペナルティゴール成功率','コンバージョン成功','コンバージョン失敗','コンバージョン成功率','ドロップゴール']};
const T={攻撃:['トライ','得点','ボールキャリー','ゲインメーター','平均ゲイン','ラインブレイク','ディフェンス突破','オフロードパス','パス'],'守備&ディシプリン':['タックル成功','タックル失敗','タックル成功率','被ターンオーバー','被ペナルティ','シンビン','レッドカード'],キック:['コンバージョン成功','コンバージョン失敗','コンバージョン成功率','PK得点','PKミス','ペナルティゴール成功率','ドロップゴール','インプレーキック'],'ブレイクダウン&セットプレー':['ラインアウト成功','ラインアウト失敗','ラインアウト成功率','ラック成功','ラック失敗','ラック勝率','スクラム勝ち','スクラム負け','スクラム勝率']};
const pct=new Set(['ペナルティゴール成功率','コンバージョン成功率','タックル成功率','ラインアウト成功率','ラック勝率','スクラム勝率']);
const demoP=[{id:'p1',name:'山田 太郎',team:'RED PHOENIX',pos:'WTB',stats:{トライ:5,得点:25,'ボールキャリー':42,'ゲインメーター':386,'ラインブレイク':8,'ディフェンス突破':13,'オフロードパス':4,'トライアシスト':3,パス:31,タックル:28,'タックルミス':3,'タックル成功':25,'プレー時間（分）':320,試合数:4}},{id:'p2',name:'佐藤 健',team:'RED PHOENIX',pos:'CTB',stats:{トライ:3,得点:15,'ボールキャリー':51,'ゲインメーター':342,'ラインブレイク':5,'ディフェンス突破':16,'オフロードパス':9,'トライアシスト':5,パス:74,タックル:39,'タックルミス':5,'タックル成功':34,'プレー時間（分）':305,試合数:4}}];
const demoT=[{id:'t1',name:'RED PHOENIX',stats:{トライ:18,得点:126,'ボールキャリー':458,'ゲインメーター':2841,'平均ゲイン':6.2,'ラインブレイク':31,'ディフェンス突破':96,'オフロードパス':42,パス:612,'タックル成功':487,'タックル失敗':54,'タックル成功率':90,'被ターンオーバー':29,'被ペナルティ':41,シンビン:2,'コンバージョン成功':14,'コンバージョン失敗':4,'コンバージョン成功率':77.8,'PK得点':7,'PKミス':2,'ペナルティゴール成功率':77.8,'インプレーキック':87,'ラインアウト成功':52,'ラインアウト失敗':7,'ラインアウト成功率':88.1,'ラック成功':324,'ラック失敗':12,'ラック勝率':96.4,'スクラム勝ち':31,'スクラム負け':5,'スクラム勝率':86.1}},{id:'t2',name:'BLUE WAVES',stats:{トライ:14,得点:102,'ボールキャリー':431,'ゲインメーター':2516,'平均ゲイン':5.8,'ラインブレイク':24,'ディフェンス突破':82,'オフロードパス':35,パス:578,'タックル成功':465,'タックル失敗':67,'タックル成功率':87.4,'被ターンオーバー':34,'被ペナルティ':48,シンビン:3,'コンバージョン成功':10,'コンバージョン失敗':4,'コンバージョン成功率':71.4,'PK得点':9,'PKミス':4,'ペナルティゴール成功率':69.2,'インプレーキック':94,'ラインアウト成功':48,'ラインアウト失敗':10,'ラインアウト成功率':82.8,'ラック成功':308,'ラック失敗':18,'ラック勝率':94.5,'スクラム勝ち':27,'スクラム負け':8,'スクラム勝率':77.1}}];
let players=JSON.parse(localStorage.getItem('rugby-players')||'null')||demoP,teams=JSON.parse(localStorage.getItem('rugby-teams')||'null')||demoT,page='home';const app=document.querySelector('#app');
const save=()=>{localStorage.setItem('rugby-players',JSON.stringify(players));localStorage.setItem('rugby-teams',JSON.stringify(teams))};
function shell(content,title){app.innerHTML=`<aside><div class="logo"><b>R</b><span>RUGBY<small>STATS HUB</small></span></div><nav><button data-page="home">▦ <i>ダッシュボード</i></button><button data-page="input">＋ <i>スタッツ入力</i></button><button data-page="players">♙ <i>選手比較</i></button><button data-page="teams">◆ <i>チーム比較</i></button></nav><div class="ready">● DATA READY</div></aside><main><header><div><small>RUGBY ANALYTICS</small><h1>${title}</h1></div><button id="csv">⇩ CSV出力</button></header>${content}</main>`;document.querySelector(`[data-page="${page}"]`).classList.add('active');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});document.querySelector('#csv').onclick=exportCsv}
function home(){let pts=teams.reduce((s,x)=>s+(+x.stats.得点||0),0);shell(`<div class="content"><section class="hero"><span>MATCHDAY DATA</span><h2>数字が、チームを<br><em>強くする。</em></h2><p>試合のスタッツを記録し、選手とチームの成長をひと目で比較。</p><button data-go="input">＋ 新しい記録を入力</button><div class="ball">RUGBY<br><b>STATS</b></div></section><div class="cards"><article><span>登録選手</span><b>${players.length}</b><small>PLAYERS</small></article><article><span>登録チーム</span><b>${teams.length}</b><small>TEAMS</small></article><article><span>チーム総得点</span><b>${pts}</b><small>POINTS</small></article><article><span>管理項目</span><b>${Object.values(P).flat().length+Object.values(T).flat().length}</b><small>METRICS</small></article></div><div class="twocol"><section class="panel"><label>PLAYER LEADERS</label><h3>トライランキング</h3>${[...players].sort((a,b)=>(b.stats.トライ||0)-(a.stats.トライ||0)).map((x,i)=>`<div class="leader"><b>0${i+1}</b><i>${x.name[0]}</i><span><strong>${x.name}</strong><small>${x.pos||'—'} · ${x.team||'—'}</small></span><em>${x.stats.トライ||0}<small>TRIES</small></em></div>`).join('')}</section><section class="team"><small>TEAM SNAPSHOT</small><h3>${teams[0]?.name||'チームを登録'}</h3><div><span><b>${teams[0]?.stats.得点||0}</b><small>得点</small></span><span><b>${teams[0]?.stats.トライ||0}</b><small>トライ</small></span><span><b>${teams[0]?.stats['タックル成功率']||0}%</b><small>タックル成功率</small></span><span><b>${teams[0]?.stats['スクラム勝率']||0}%</b><small>スクラム勝率</small></span></div></section></div></div>`,'ダッシュボード');document.querySelector('[data-go]').onclick=()=>{page='input';render()}}
function input(){shell(`<div class="content"><div class="tabs"><button class="on" data-type="player">選手スタッツ</button><button data-type="team">チームスタッツ</button></div><section class="panel form" id="form"></section></div>`,'スタッツ入力');drawForm('player');document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-type]').forEach(x=>x.classList.remove('on'));b.classList.add('on');drawForm(b.dataset.type)})}
function drawForm(type){let secs=type==='player'?P:T;document.querySelector('#form').innerHTML=`<div class="formhead"><label>NEW RECORD</label><h2>${type==='player'?'選手':'チーム'}スタッツ入力</h2><p>未入力項目は0として保存されます。</p></div><div class="identity"><label>${type==='player'?'選手名':'チーム名'}<input id="name" placeholder="名前を入力"></label>${type==='player'?'<label>所属チーム<input id="team"></label><label>ポジション<input id="pos" placeholder="例：WTB"></label>':''}</div>${Object.entries(secs).map(([cat,fs])=>`<details open><summary>${cat}<small>${fs.length}項目</small></summary><div class="grid">${fs.map(f=>`<label>${f}<div><input type="number" min="0" step="${pct.has(f)||f==='平均ゲイン'?'.1':'1'}" data-stat="${f}" value="0">${pct.has(f)?'<i>%</i>':''}</div></label>`).join('')}</div></details>`).join('')}<div class="save"><span>保存後、比較画面へ反映されます</span><button id="save">保存する</button></div>`;document.querySelector('#save').onclick=()=>{let name=document.querySelector('#name').value.trim();if(!name)return alert('名前を入力してください');let stats={};document.querySelectorAll('[data-stat]').forEach(i=>stats[i.dataset.stat]=+i.value||0);let rec={id:crypto.randomUUID(),name,stats};if(type==='player'){rec.team=document.querySelector('#team').value;rec.pos=document.querySelector('#pos').value;players.push(rec)}else teams.push(rec);save();alert('保存しました');drawForm(type)}}
function compare(type){let data=type==='player'?players:teams,secs=type==='player'?P:T,sel=data.slice(0,3);shell(`<div class="content"><section class="panel compare"><div class="formhead"><label>COMPARE</label><h2>${type==='player'?'選手':'チーム'}を比較</h2><p>最大3件を横並びで比較できます。</p></div>${data.length?`<div class="selects">${[0,1,2].map((_,i)=>`<select data-sel="${i}"><option value="">未選択</option>${data.map(x=>`<option value="${x.id}" ${sel[i]?.id===x.id?'selected':''}>${x.name}</option>`).join('')}</select>`).join('')}</div><div class="tablewrap" id="table"></div>`:'<div class="empty">記録がありません。入力画面から追加してください。</div>'}</section><section class="panel records"><label>MANAGE DATA</label><h3>登録済みデータ</h3>${data.map(x=>`<div><i>${x.name[0]}</i><span><b>${x.name}</b><small>${type==='player'?(x.pos||'—')+' · '+(x.team||'—'):(x.stats.得点||0)+' POINTS'}</small></span><button data-del="${x.id}">削除</button></div>`).join('')}</section></div>`,type==='player'?'選手比較':'チーム比較');if(data.length){drawTable(sel,secs,type);document.querySelectorAll('[data-sel]').forEach(s=>s.onchange=()=>{sel[+s.dataset.sel]=data.find(x=>x.id===s.value);drawTable(sel.filter(Boolean),secs,type)})}document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('削除しますか？')){type==='player'?players=players.filter(x=>x.id!==b.dataset.del):teams=teams.filter(x=>x.id!==b.dataset.del);save();compare(type)}})}
function drawTable(sel,secs,type){document.querySelector('#table').innerHTML=`<table><thead><tr><th>スタッツ項目</th>${sel.map(x=>`<th><i>${x.name[0]}</i><b>${x.name}</b><small>${type==='player'?(x.pos||'—')+' · '+(x.team||'—'):'TEAM TOTAL'}</small></th>`).join('')}</tr></thead><tbody>${Object.entries(secs).map(([cat,fs])=>`<tr class="cat"><td colspan="${sel.length+1}">${cat}</td></tr>${fs.map(f=>{let vals=sel.map(x=>+x.stats[f]||0),max=Math.max(...vals);return`<tr><td>${f}</td>${vals.map(v=>`<td class="${v===max&&v>0?'best':''}">${pct.has(f)?v.toFixed(1)+'%':v.toLocaleString()}${v===max&&v>0?'<small>BEST</small>':''}</td>`).join('')}</tr>`}).join('')}`).join('')}</tbody></table>`}
function exportCsv(){let rows=[['種別','名前','所属チーム','ポジション','カテゴリ','項目','値']];players.forEach(r=>Object.entries(P).forEach(([c,fs])=>fs.forEach(f=>rows.push(['選手',r.name,r.team,r.pos,c,f,r.stats[f]||0]))));teams.forEach(r=>Object.entries(T).forEach(([c,fs])=>fs.forEach(f=>rows.push(['チーム',r.name,'','',c,f,r.stats[f]||0]))));let q=v=>'"'+String(v??'').replaceAll('"','""')+'"',blob=new Blob(['\ufeff'+rows.map(r=>r.map(q).join(',')).join('\r\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='rugby-stats.csv';a.click()}
function render(){({home,input,players:()=>compare('player'),teams:()=>compare('team')}[page])()}render();

